"""adicionar reservation_id em seats

Revision ID: cfa5c4ee187b
Revises: eaa8511d525f
Create Date: 2026-08-18 08:27:18.082595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa5c4ee187b'
down_revision: Union[str, Sequence[str], None] = 'eaa8511d525f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('reservation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'seats', 'reservations', ['reservation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seats', type_='foreignkey')
    op.drop_column('seats', 'reservation_id')
    # ### end Alembic commands ###
